- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/cicd/Dockerfile
        dest: /home/ec2-user
        mode: '0644'

    - name: Install Docker using shell command
      ansible.builtin.shell: sudo yum install docker -y

        

    - name: start docker
      ansible.builtin.command:
        cmd: service start docker 

    - name: permission
      ansible.builtin.command:
        cmd: chmod 777 /var/run/docker.sock

    - name: Run the Linux command
      ansible.builtin.command:
        cmd: docker build -t sarathi .

    - name: remove previous container
      ansible.builtin.command:
        cmd: docker rm -f prakash

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name prakash -p 8083:8080 sarathi


    - name: remove file
      ansible.builtin.command:
        cmd: rm -f /home/ec2-user/Dockerfile

    

    




