- name: run 
  hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
    
    - name: run script
      ansible.builtin.command:
        cmd: kubectl apply -f /var/lib/jenkins/workspace/my/selvapod.yml
