apiVersion: v1
kind: Pod
metadata:
  name: vicky-app22
  labels:
    name: MyAppss
spec:
  containers:
  - name: vicky
    image: ganesh20101/java-app
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: my-dockerhub-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: my-servicess
spec:
  type: NodePort
  selector:
    name: MyAppss
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30014
